### ISSUE TITLE
Вариантивность продуктов предусмотрена?

### ISSUE THREAD

**Issue by aiiddqd** [sgtpep/woocommerce-1c#1]
Привет!
Мы планируем настроить этот плагин для связки 1С УТ и сайта с вариативными продуктами.
Сейчас плагин предусматривает такой механизм? Или нужно будет дописать?

**Comment by sgtpep** [comment]
Привет!

Поддержка вариативных товаров закладывалась (https://raw.githubusercontent.com/sgtpep/woocommerce-1c/assets/screenshot-3.png, https://raw.githubusercontent.com/sgtpep/woocommerce-1c/assets/screenshot-4.png), но какие-то специфичные юзкейсы могут потребовать кастомизации через хуки и/или доработки плагина.

**Comment by aiiddqd** [comment]
Понял. Попробуем.
