### ISSUE TITLE
Ошибка c1c_error(PHP Unknown Error: Undefined offset exchange/import.php on line 136

### ISSUE THREAD

**Issue by ipatovda** [sgtpep/woocommerce-1c#20]
PHP Unknown Error: Undefined offset: 3 in public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange/import.php on line 136.

#0 wc1c_error(PHP Unknown Error: Undefined offset: 3 in public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange/import.php on line 136., PHP Unknown Error) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:142]
#1 wc1c_strict_error_handler(8, Undefined offset: 3, public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange/import.php, 136, Array ([is_full] => 1,[names] => Array ([0] => КоммерческаяИнформация,[1] => Каталог,[2] => Товары,[3] => Товар,[4] => ЗначенияРеквизитов,[5] => ЗначениеРеквизита,[6] => Значение),[depth] => 6,[name] => Значение,[data] => import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpeg#[Elizavecca] ,[wc1c_groups] => Array (),[wc1c_group_depth] => -1,[wc1c_property] => Array ([Ид] => 83959b81-a695-45d1-b6df-938c86ecab97,[Наименование] => Основной поставщик,[ТипЗначений] => Справочник,[ВариантыЗначений] => Array (),[ДляТоваров] => true),[wc1c_product] => Array ([ХарактеристикиТовара] => Array (),[ЗначенияСвойств] => Array ([0] => Array ([Ид] => 83959b81-a695-45d1-b6df-938c86ecab97,[Значение] => Array ([0] => ))),[ЗначенияРеквизитов] => Array ([18446744073709551615] => Array ([Значение] => Array ([0] => )),[0] => Array (),[1] => Array ([Наименование] => ОписаниеФайла),[2] => Array ([Значение] => Array ([0] => ))),[Ид] => 9a11efec-b55c-11e6-8113-d43d7eeceb89,[Штрихкод] => 8809339903523,[Артикул] => 903523,[Наименование] => [Elizavecca] Маска д/сухих и поврежденный волос КОЛЛАГЕНОВАЯ Collagen Ceramide Coating Protein,100мл,[БазоваяЕдиница] => шт,[Группы] => Array ([0] => 29416c33-54d8-11e7-80c5-94de8014c4e0),[ЗначениеРеквизита] =>

,[Картинка] => Array ([0] => import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpeg)),[i] => 3)) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange/import.php:136]
#2 wc1c_import_character_data_handler(1, Array ([0] => КоммерческаяИнформация,[1] => Каталог,[2] => Товары,[3] => Товар,[4] => ЗначенияРеквизитов,[5] => ЗначениеРеквизита,[6] => Значение), 6, Значение, import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpeg#[Elizavecca] ) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:375]
#3 wc1c_xml_character_data_handler(Resource id #180, import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpeg#[Elizavecca] )
#4 xml_parse(Resource id #180, �ниеВФорматеHTMLНаименование>
<Значение>Маска для волос торговой марки Elizavecca
Milky Piggy Collagen Ceramide Coating Protein Treatment
В составе коллаген, комплекс керамидов, соевый белок, аллантоин, растительные экстракты и протеины пшеницы. Подходит для окрашеных, поврежденных термообработкой волос. Уникальный состав маски обеспечивает питание и увлажнение. Обволакивает структуру волоса, защищая от вредного внешнего воздействия. Применение: После использования шампуня, просушить волосы полотенцем. Нанести небольшое количество маски и распределить по всей длине. Смыть через 5 минут . Для более сильного эффекта можно держать маску до 20 минут. Состав: Water, Cetyl Alcohol, Stearyl Alcohol, Amodimethicone, Cetrimonium Chloride, Trideceth-12, Behentrimonium Chloride, Glycerin , Cyclopentasiloxane , Dimethicone , Silk Amino Acids, Ceramide 3, Tocopheryl Acetate, Hydrolyzed Collagen, Hydrolyzed Keratin, Gelatin, Avena Sativa (Oat) Kernel Extract, Hydrolyzed Corn Protein, Hydrolyzed Wheat Protein, Hydrolyzed Soy Protein, Apium Graveolens (Celery) Extract , Brassica Oleracea Capitata (Cabbage) Leaf Extract, Oryza Sativa (Rice) Extract, Solanum Lycopersicum (Tomato) Fruit Extract , Brassica Rapa (Turnip) Leaf Extract, Daucus Carota Sativa (Carrot) Root Extract, Brassica Oleracea Italica (Broccoli) Extract, Butylene Glycol, Rehmannia Chinensis Root Extract, Cornus Officinalis Fruit Extract, Alisma Orientale Tuber Extract, Dioscorea Japonica Root Extract, Poria Cocos Extract, Paeonia Suffruticosa Root Extract, Panthenol, Caramel, Citric Acid, Methylchloroisothiazolinone, Methylisothiazolinone, perfum. Только для наружного применения. Хранить в недоступном для детей месте. В случае появления раздражения, немедленно прекратить использование. Хранить при температуре от +5*С до +25*С. Производитель:Miz Trade Co., Ltd. Dogok-Dong, Gangnam-Gu, (Gujeong bldg, 3 Floor), Республика Корея. Импортер/Организация, принимающая претензии: ООО „АЙКОН”, г.Владивосток, Суханова 4 Б, т.89841508888 123.ru. Номер партии: см. на упаковке. Срок годности: 36 месяцев. Годен до: см. на упаковке (гг/мм/дд). После вскрытия использовать в течении 12 месяцев. Содержимое: 100 мл. арт. 903523. Товар сертифицирован.
Значение>
ЗначениеРеквизита>
<Картинка>import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpegКартинка>
<ЗначенияСвойств>
<ЗначенияСвойства>
<Ид>83959b81-a695-45d1-b6df-938c86ecab97Ид>
<Значение/>
ЗначенияСвойства>
ЗначенияСвойств>
<ЗначенияРеквизитов>
<ЗначениеРеквизита>
<Наименование>ОписаниеФайлаНаименование>
<Значение>import_files/9a/9a11efec-b55c-11e6-8113-d43d7eeceb89_9a11efee-b55c-11e6-8113-d43d7eeceb89.jpeg#[Elizavecca] Маска д/сухих и поврежденный волос КОЛЛАГЕНОВАЯ Collagen Ceramide Coating Protein,100млЗначение>
ЗначениеРеквизита>
<Значени, ) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:398]
#5 wc1c_xml_parse(Resource id #179) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:448]
#6 wc1c_mode_import(catalog, import.xml) called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:508]
#7 wc1c_exchange() called at [public_html/wp-content/plugins/woocommerce-and-1centerprise-data-exchange/exchange.php:533]
#8 wc1c_template_redirect() called at [public_html/wp-includes/class-wp-hook.php:286]
#9 WP_Hook->apply_filters(, Array ([0] => )) called at [public_html/wp-includes/class-wp-hook.php:310]
#10 WP_Hook->do_action(Array ([0] => )) called at [public_html/wp-includes/plugin.php:453]
#11 do_action(template_redirect) called at [public_html/wp-includes/template-loader.php:12]
#12 require_once(public_html/wp-includes/template-loader.php) called at [public_html/wp-blog-header.php:19]
#13 require(public_html/wp-blog-header.php) called at [public_html/index.php:17]

Request URI: https://domain.ru:443/?wc1c=exchange?type=catalog&...
Server API: apache2handler
Memory limit: 268435456
Maximum POST size: 1047527424
PHP version: 7.2.5
WordPress version: 4.9.8
Plugin version: 0.7r1466555

rollback 

Помогите решить проблему. Спасибо

**Comment by Kucenkov** [comment]
решил эту пробелму год назад, помойму есть решение на форуме wordpress, попробуй выставить параметры, предварительно сохранив свои настройки:

memory_limit = 4G
max_execution_time = 500
upload_max_filesize = 1G
post_max_size = 1G
max_input_time = 500
max_file_uploads = 1000
file_limit = -1

**Comment by Kucenkov** [comment]
и еще выстави в 1с количество товаров в порции 
http://prntscr.com/klcjj0

**Comment by ipatovda** [comment]
Спасибо большое, попробую.


>Вторник, 21 августа 2018, 22:17 +03:00 от Kucenkov <notifications@github.com>:
>
>и еще выстави в 1с количество товаров в порции
>http://prntscr.com/klcjj0
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Дима Ипатов

**Comment by itkos** [comment]
Доброго времени суток! Уже как третьи сутки мучаюсь с этим обменом. У меня woocommerce и 1С УНФ. Пробовал выгрузить 1000 позиций - ошибка копирования файла. Общался с хостером besthosting.ua все лимиты подняты до предела!

Решил сбелать ручной обмен. Выгрузил в каталог файлы для обмена, загрузил их в папку на хостинг, перехожу по ссылкам ***/?type=catalog&mode=import&filename=import.xml и ***/?type=catalog&mode=import&filename=offers.xml и ничего не происходит вообще, просто открывается страница и всё....

Ребята!ПОМОГИТЕ ПОЖАЛУЙСТА ЗАПУСТИТЬ ЭТОТ ОБМЕН!!! ЗАСТРЕЛЮСЬ....

**Comment by itkos** [comment]
@sel1kkk 
Добрый день! У Вас получилось настроить обмен?

**Comment by ipatovda** [comment]
> @sel1kkk
> Добрый день! У Вас получилось настроить обмен?

Да получилось. Но у меня была ошибка непонятная в самих карточках товара, 1 из товаров был с непонятным полем описание, чтото типа ОписаниеТовараХтмл, а в других было просто поле описание. Исправили в 1с и все прошло...

Я делал вручную выгрузку, и смотрел на каком товаре она крашилась, потом лез в xml и удалял данный товар, пока все товары не удалил которые мешали, так и продолжалось, и только потом при сравнении рабочих и не рабочих товаров, понял в чем дело. 

Вот как-то так...

**Comment by itkos** [comment]
@sel1kkk 
У меня вот такая  ошибка:
Интерактивный обмен
02.10.2018 17:35:21 Запуск выгрузки товаров
02.10.2018 17:39:21 Завершено формирование файлов выгрузки товаров
Выгружено товаров: 1 057
предложений: 1 056
картинок: 3 563
файлов: 0

В том числе для каталога Основной каталог:
товаров: 1 057
предложений: 1 056
картинок: 3 563
файлов: 0

02.10.2018 18:28:49 Выгрузка на сайт завершилась с ошибками.
import.xml: Произошла ошибка на стороне сервера. Получен неизвестный статус импорта.
Ответ сервера: 
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.11.3</center>
</body>
</html>

02.10.2018 18:28:56 Завершена выгрузка товаров

может сталкивались с такой?
А как в ручную потом заливали на хостинг и что делали чтобы плагин подхватил xml? Я пробовал писать "***/?type=catalog&mode=import&filename=import.xml", в инструкции написано...но ничего не выходит...

**Comment by ipatovda** [comment]
> @sel1kkk
> У меня вот такая ошибка:
> Интерактивный обмен
> 02.10.2018 17:35:21 Запуск выгрузки товаров
> 02.10.2018 17:39:21 Завершено формирование файлов выгрузки товаров
> Выгружено товаров: 1 057
> предложений: 1 056
> картинок: 3 563
> файлов: 0
> 
> В том числе для каталога Основной каталог:
> товаров: 1 057
> предложений: 1 056
> картинок: 3 563
> файлов: 0
> 
> 02.10.2018 18:28:49 Выгрузка на сайт завершилась с ошибками.
> import.xml: Произошла ошибка на стороне сервера. Получен неизвестный статус импорта.
> Ответ сервера:
> <title>504 Gateway Time-out</title>
> # 504 Gateway Time-out
> nginx/1.11.3
> 
> 02.10.2018 18:28:56 Завершена выгрузка товаров
> 
> может сталкивались с такой?

А порциями пробовали? Или к примеру поставить 10 товаров на выгрузку...

**Comment by itkos** [comment]
@sel1kkk Пробовал 1 товар - выгрузило, пробовал группу выгрузило но не проставило цены...а вот 1000 товаров уже не грузит....

Вы максимум сколько выгружали?

**Comment by ipatovda** [comment]
> @sel1kkk
> У меня вот такая ошибка:
> Интерактивный обмен
> 02.10.2018 17:35:21 Запуск выгрузки товаров
> 02.10.2018 17:39:21 Завершено формирование файлов выгрузки товаров
> Выгружено товаров: 1 057
> предложений: 1 056
> картинок: 3 563
> файлов: 0
> 
> В том числе для каталога Основной каталог:
> товаров: 1 057
> предложений: 1 056
> картинок: 3 563
> файлов: 0
> 
> 02.10.2018 18:28:49 Выгрузка на сайт завершилась с ошибками.
> import.xml: Произошла ошибка на стороне сервера. Получен неизвестный статус импорта.
> Ответ сервера:
> <title>504 Gateway Time-out</title>
> # 504 Gateway Time-out
> nginx/1.11.3
> 
> 02.10.2018 18:28:56 Завершена выгрузка товаров
> 
> может сталкивались с такой?
> А как в ручную потом заливали на хостинг и что делали чтобы плагин подхватил xml? Я пробовал писать "***/?type=catalog&mode=import&filename=import.xml", в инструкции написано...но ничего не выходит...

Файлы как я понял в любом случае выгружаются на сервер, посмотреть их можно в папке /wp-content/uploads/woocommerce-1c/catalog

**Comment by ipatovda** [comment]
> @sel1kkk Пробовал 1 товар - выгрузило, пробовал группу выгрузило но не проставило цены...а вот 1000 товаров уже не грузит....
> 
> Вы максимум сколько выгружали?

У нас не большой каталог примерно 300 наименований. 
Это колво выгружает, на виртуальном хостинге норм. 

А вам скорей всего лимиты вашего хостинга не дают это сделать. Поэтому и таймаут 504

**Comment by sel1kkk** [comment]
--




> > @sel1kkk Пробовал 1 товар - выгрузило, пробовал группу выгрузило но не проставило цены...а вот 1000 товаров уже не грузит....
> > Вы максимум сколько выгружали?
> 
> У нас не большой каталог примерно 300 наименований.
> Это колво выгружает, на виртуальном хостинге норм.
> 
> А вам скорей всего лимиты вашего хостинга не дают это сделать. Поэтому и таймаут 504

**Comment by itkos** [comment]
@sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
Сейчас на сервере получается архив который распаковывается.
В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?

**Comment by itkos** [comment]
> 
> 
> --
> 
> > > @sel1kkk Пробовал 1 товар - выгрузило, пробовал группу выгрузило но не проставило цены...а вот 1000 товаров уже не грузит....
> > > Вы максимум сколько выгружали?
> > 
> > 
> > У нас не большой каталог примерно 300 наименований.
> > Это колво выгружает, на виртуальном хостинге норм.
> > А вам скорей всего лимиты вашего хостинга не дают это сделать. Поэтому и таймаут 504

мой .htaccess
php_value post_max_size 2048M
php_value upload_max_filesize 2048M
php_value max_input_vars 20000
php_value max_file_uploads 100000
php_value memory_limit 2048M
php_value max_input_time 60000
php_value request_terminate_timeout 0
php_value max_execution_time 900000
php_value file_limit -1

можно ваш для сравнения?

**Comment by ipatovda** [comment]
> @sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
> Сейчас на сервере получается архив который распаковывается.
> В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?




Да, при поиске ошибки, http://example.com/wc1c/exchange/?type=catalog&mode=import&filename=import.xml

**Comment by ipatovda** [comment]
> > --
> > > > @sel1kkk Пробовал 1 товар - выгрузило, пробовал группу выгрузило но не проставило цены...а вот 1000 товаров уже не грузит....
> > > > Вы максимум сколько выгружали?
> > > 
> > > 
> > > У нас не большой каталог примерно 300 наименований.
> > > Это колво выгружает, на виртуальном хостинге норм.
> > > А вам скорей всего лимиты вашего хостинга не дают это сделать. Поэтому и таймаут 504
> 
> мой .htaccess
> php_value post_max_size 2048M
> php_value upload_max_filesize 2048M
> php_value max_input_vars 20000
> php_value max_file_uploads 100000
> php_value memory_limit 2048M
> php_value max_input_time 60000
> php_value request_terminate_timeout 0
> php_value max_execution_time 900000
> php_value file_limit -1
> 
> можно ваш для сравнения?


# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

у меня стандарт

**Comment by itkos** [comment]
> 
> 
> > @sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
> > Сейчас на сервере получается архив который распаковывается.
> > В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?
> 
> Да, при поиске ошибки, http://example.com/wc1c/exchange/?type=catalog&mode=import&filename=import.xml

и что происходит после перехода по этой ссылке?

**Comment by ipatovda** [comment]
> > > @sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
> > > Сейчас на сервере получается архив который распаковывается.
> > > В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?
> > 
> > 
> > Да, при поиске ошибки, http://example.com/wc1c/exchange/?type=catalog&mode=import&filename=import.xml
> 
> и что происходит после перехода по этой ссылке?

Ждем пока догрузится, и или success выдаст, или ошибку

**Comment by itkos** [comment]
> 
> 
> > > > @sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
> > > > Сейчас на сервере получается архив который распаковывается.
> > > > В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?
> > > 
> > > 
> > > Да, при поиске ошибки, http://example.com/wc1c/exchange/?type=catalog&mode=import&filename=import.xml
> > 
> > 
> > и что происходит после перехода по этой ссылке?
> 
> Ждем пока догрузится, и или success выдаст, или ошибку

Т.е. скрипт должен что то выдать всё равно? У меня просто загружается страница и всё. Вы в каком браузере пробовали?

**Comment by ipatovda** [comment]
> > > > > @sel1kkk файлы выгружаются, хоть до сегодня и файлы не выгружались до конца :-)
> > > > > Сейчас на сервере получается архив который распаковывается.
> > > > > В инструкции написано что можно в ручную запустить введя ссылку, вы пробовали?
> > > > 
> > > > 
> > > > Да, при поиске ошибки, http://example.com/wc1c/exchange/?type=catalog&mode=import&filename=import.xml
> > > 
> > > 
> > > и что происходит после перехода по этой ссылке?
> > 
> > 
> > Ждем пока догрузится, и или success выдаст, или ошибку
> 
> Т.е. скрипт должен что то выдать всё равно? У меня просто загружается страница и всё. Вы в каком браузере пробовали?

Да он в любом случае чтото напишет, или success, commit или выдаст ошибку

от браузера не зависит, вместо  http://example.com/wc1c/exchange/ вставляем вашу ссылку, и ждем. 

у меня ожидание при 100-200 товаров примерно минута
