### ISSUE TITLE
Плагин не работает в последней версии Woocommerce

### ISSUE THREAD

**Issue by ghost** [sgtpep/woocommerce-1c#4]
https://wordpress.org/support/topic/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-%D0%BF%D1%80%D0%B8-%D0%B2%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B5-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2-%D0%B8%D0%B7-1%D0%A1?replies=2#post-8702477  - здесь описание правок, которые решили проблему.

**Comment by sgtpep** [comment]
Приветствую, @mmice!

Был бы очень признателен, если бы у вас получилось прислать эти правки в виде пулл-реквеста.

**Comment by ghost** [comment]
Что-то не получается (( я, правда, впервые к гит общаюсь (
Могу прислать просто архив.

**Comment by sgtpep** [comment]
Давайте попробуем с архивом.

**Comment by ghost** [comment]
https://drive.google.com/file/d/0B1EqzhZlRLuRN21yQ0tjLWxaS3c/view?usp=sharing

**Comment by sgtpep** [comment]
Спасибо! Внёс эти правки (в немного ином виде) в версию на github и в версию на wordpress.org (номер версии не обновлял, можно удалить и установить вновь из админки wordpress). Буду благодарен узнать об их работоспособности.
