### ISSUE TITLE
Ошибочный откат изменений пулл-реквеста 60.

### ISSUE THREAD

**Issue by Lomerill** [sgtpep/woocommerce-1c#61]
Судя по всему, https://github.com/sgtpep/woocommerce-1c/pull/59 был принят после моего https://github.com/sgtpep/woocommerce-1c/pull/60 и изменения были откачены.

**Comment by sgtpep** [comment]
Да, каким-то образом изменения потерялись (пока не понятно как, возможно, неправильный порядок действий с git-svn, т.к. просто PR не должен был перезатереть изменения другого PR), прошу прощения. Вернул их обратно.
