### ISSUE TITLE
Undefined property: wpdb::$woocommerce_termmeta

### ISSUE THREAD

**Issue by ghost** [sgtpep/woocommerce-1c#7]
Добрый вечер! Похоже, снова какая-то проблема стряслась (
https://vapegood.ru/wc1c/exchange?type=catalog&mode=import&filename=import.xml - ругается на сабж, а дальше... я так понимаю, обрубает процесс?

**Comment by sgtpep** [comment]
Здравствуйте! А не могли бы привести полный текст сообщения об ошибке с трейсбеком? (Чтобы посмотреть, в каком месте кода ошибка.)

**Comment by ghost** [comment]
Уже побороли. Затесалась версия с репозитория вордпресса.
Сейчас только нотис 

Заказы: Обработка импортированного файла: не найдены новые заказы; обнаружены изменения (1) в заказах, магазин вернул п»їPHP Unknown Error: Undefined index: РўРѕРІР°СЂС‹ in /.../plugins/woocommerce-and-1centerprise-data-exchange/exchange/orders.php on line 323. в ответ на отправленные сведения о заказах

**Comment by sgtpep** [comment]
Добавил проверку наличия этого индекса, на отсутствие которого выводится ошибка.
